theme: jekyll-theme-cayman
title : "LookUp : ✨Stars✨ and how we see them"
color:
  header: "#fff"
  gradient_left: "#42f5b0"
  gradient_right: "#6e04c4"
color.section_title : "#6e04c4"
logo_url: "https://ibb.co/bvk3Tg2"
