theme: jekyll-theme-cayman
title : Look up, stars and how we see them
color:
  header: "#fff"
  gradient_left: "#0acc65"
  gradient_right: "#9904de"
color.section_title : "#2e0242"
logo_url: "https://ibb.co/bvk3Tg2"
